version: '3.8'
services:
  liberchat:
    build:
      context: .
      args:
        - BRANCH=${BRANCH:-Liberchat6.1.16}
    container_name: liberchat-autonome
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
      - PORT=3000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.liberchat.rule=Host(`ton-domaine.com`)"
      - "traefik.http.routers.liberchat.entrypoints=websecure"
      - "traefik.http.routers.liberchat.tls.certresolver=le"
    # ---------------------------------------------
    # Pour la plupart des utilisateurs :
    # Lancez simplement la commande ci-dessous :
    # ALLOWED_DOMAINS="https://votre-domaine.com" docker-compose up --build -d
    # ---------------------------------------------
    # Pour les développeurs (optionnel) :
    # Si vous voulez tester vos modifications de code en direct :
    # 1. Décommentez les 2 lignes ci-dessous :
    #    volumes:
    #      - ../:/app
    # 2. Lancez avec :
    #    NODE_ENV=development docker-compose up --build
    # (Vous pouvez ignorer cette partie si vous ne faites que déployer)
    # ---------------------------------------------
    # Pour choisir une branche ou un tag spécifique :
    # (optionnel, à utiliser seulement si vous voulez une version précise)
    # Exemple :
    # BRANCH=dev docker-compose up --build -d
    # (Sinon, laissez vide pour utiliser la version par défaut)
    # ---------------------------------------------
    # Pour accéder au conteneur depuis d'autres appareils du réseau local,
    # assurez-vous que le port 3000 est bien exposé (déjà le cas ci-dessus)
    # et que votre pare-feu autorise les connexions entrantes sur ce port.
    #
    # Pour autoriser l'accès réseau local en production, ajoutez http://<IP>:3000
    # dans la variable ALLOWED_DOMAINS lors du lancement ou via le script.
  nginx:
    build:
      context: ./nginx
    container_name: liberchat-nginx
    depends_on:
      - liberchat
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=ton.email@domaine.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8080:8080"
      - "4443:443"
      - "8081:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped
